[routes]
GET / = Http\Controllers\HomeController->index
GET /history = Http\Controllers\HistoryController->index
; PUT /api/projects/@slug = Http\Controllers\ProjectController->update

; GET /api/modules/@project_id = Http\Controllers\ModuleController->index

; POST /api/login = Http\Controllers\SessionController->store
; POST /api/verify = Http\Controllers\SessionController->show
; DELETE /api/logout = Http\Controllers\SessionController->destroy

; POST /api/email = Http\Controllers\EmailController->store
